export const skills = {
  gtmAndRevops: [
    "GTM Engineering",
    "Revenue Operations (RevOps)",
    "Sales Operations",
    "GTM Strategy",
    "Funnel Analytics",
    "Pipeline Management",
    "Lead Scoring",
    "Sales Forecasting",
    "CAC / MQL Optimization",
    "KPI Frameworks",
  ],
  salesAnalytics: [
    "Sales Performance Reporting",
    "Pipeline Hygiene",
    "Attribution Analysis",
    "Conversion Funnel Analysis",
    "Executive Revenue Dashboards",
    "Power BI",
    "Tableau",
    "SQL",
  ],
  aiAutomation: [
    "GTM Workflow Automation",
    "AI Sales Enablement Tools",
    "Prompt Engineering",
    "Lead Qualification Bots",
    "Predictive Lead Scoring",
    "Machine Learning (XGBoost)",
    "RAG",
  ],
  programmingAnalytics: [
    "Python",
    "SQL",
    "Pandas",
    "NumPy",
    "Excel / VBA",
    "Next.js / TypeScript",
    "Data Visualization",
  ],
  crmSystems: [
    "Salesforce",
    "HubSpot",
    "LeadSquared",
    "Aline CRM",
    "ExaCare",
    "PCC",
  ],
  collaboration: [
    "Sales Team Enablement",
    "Executive Reporting",
    "Stakeholder Management",
    "Data Storytelling",
    "Business Process Improvement",
  ],
} as const;
